services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: moviebrowser3
      POSTGRES_USER: moviebrowser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data

volumes: {}
