services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-moviebrowser3}
      POSTGRES_USER: ${DB_USERNAME:-moviebrowser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data

volumes: {}
